user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
api:
    resource: "."
    type:     "api"
    prefix:   "api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"
